version: '2'
services:
  node1:
    build: .
    environment:
      - REDIS_HOST=redis1
      - ME=node1
      - NODE1=node2
      - NODE2=node3
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ruby http_server.rb
  redis1:
    image: redis

  node2:
    build: .
    environment:
      - REDIS_HOST=redis2
      - ME=node2
      - NODE1=node1
      - NODE2=node3
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    command: ruby http_server.rb
  redis2:
    image: redis

  node3:
    build: .
    environment:
      - REDIS_HOST=redis3
      - ME=node3
      - NODE1=node1
      - NODE2=node2
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    command: ruby http_server.rb
  redis3:
    image: redis
